# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\create_table_create.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(816, 649)
        Form.setStyleSheet("#Form {\n"
"border-style: solid;\n"
"border-color:  #f2f7f5;\n"
"background: #cfe2da; \n"
"\n"
"}\n"
"\n"
"#Form QListWidget {\n"
"    background-color: #F0FCF7;\n"
"   border-radius: 10px;\n"
"    padding: 5px 5px 5px 5px;\n"
"    text-align: center;\n"
"    color:#41312b;\n"
"}\n"
"\n"
"#Form QPushButton {\n"
"    background-color: #587b6d;\n"
"   border-radius: 10px;\n"
"    padding: 5px 5px 5px 5px;\n"
"    text-align: center;\n"
"    color:#f2b198;\n"
"}\n"
"\n"
"#Form QLineEdit {\n"
"    background-color: #F0FCF7;\n"
"   border-radius: 10px;\n"
"    padding: 5px 5px 5px 5px;\n"
"    text-align: center;\n"
"    color:#41312b;\n"
"}\n"
"\n"
"#Form QLabel {\n"
"   border-radius: 10px;\n"
"    padding: 5px 5px 5px 5px;\n"
"    text-align: center;\n"
"    color:#41312b;\n"
"}\n"
"\n"
"#Form QComboBox {\n"
"    background-color: #587b6d;\n"
"   border-radius: 10px;\n"
"    padding: 5px 5px 5px 100px;\n"
"    text-align: center;\n"
"    color:#f2b198;\n"
"    \n"
"}\n"
"\n"
"#Form QPushButton:hover {\n"
"    background-color: #408d49;\n"
"   border-radius: 10px;\n"
"       color:#fde1d6;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.widget = QtWidgets.QWidget(self.widget_2)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_12 = QtWidgets.QLabel(self.widget_3)
        self.label_12.setStyleSheet("")
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 3, 0, 1, 1)
        self.comboBox_direction = QtWidgets.QComboBox(self.widget_3)
        self.comboBox_direction.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_direction.setFont(font)
        self.comboBox_direction.setStyleSheet("")
        self.comboBox_direction.setObjectName("comboBox_direction")
        self.comboBox_direction.addItem("")
        self.comboBox_direction.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_direction, 6, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.widget_3)
        self.comboBox.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_3.addWidget(self.comboBox, 5, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 7, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widget_3, 0, 0, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_6 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("72")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("")
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget_4)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 2, 0, 1, 1)
        self.lineDateInput = QtWidgets.QLineEdit(self.widget_4)
        self.lineDateInput.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineDateInput.setFont(font)
        self.lineDateInput.setStyleSheet("")
        self.lineDateInput.setObjectName("lineDateInput")
        self.gridLayout_5.addWidget(self.lineDateInput, 1, 0, 1, 1)
        self.listDatesWeekday = QtWidgets.QListWidget(self.widget_4)
        self.listDatesWeekday.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.listDatesWeekday.setFont(font)
        self.listDatesWeekday.setStyleSheet("")
        self.listDatesWeekday.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listDatesWeekday.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listDatesWeekday.setObjectName("listDatesWeekday")
        self.gridLayout_5.addWidget(self.listDatesWeekday, 1, 1, 3, 1)
        self.label_13 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("72")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("")
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 0, 0, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.widget_4)
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_16 = QtWidgets.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setFamily("72")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("")
        self.label_16.setObjectName("label_16")
        self.gridLayout_8.addWidget(self.label_16, 0, 0, 1, 1)
        self.line_Selection_agency = QtWidgets.QLineEdit(self.widget_5)
        self.line_Selection_agency.setEnabled(False)
        self.line_Selection_agency.setStyleSheet("")
        self.line_Selection_agency.setObjectName("line_Selection_agency")
        self.gridLayout_8.addWidget(self.line_Selection_agency, 3, 0, 1, 1)
        self.line_Selection_format = QtWidgets.QLineEdit(self.widget_5)
        self.line_Selection_format.setEnabled(False)
        self.line_Selection_format.setStyleSheet("")
        self.line_Selection_format.setObjectName("line_Selection_format")
        self.gridLayout_8.addWidget(self.line_Selection_format, 2, 0, 1, 1)
        self.line_Selection_date_range = QtWidgets.QLineEdit(self.widget_5)
        self.line_Selection_date_range.setEnabled(False)
        self.line_Selection_date_range.setStyleSheet("")
        self.line_Selection_date_range.setObjectName("line_Selection_date_range")
        self.gridLayout_8.addWidget(self.line_Selection_date_range, 7, 0, 1, 1)
        self.line_Selection_trips = QtWidgets.QLineEdit(self.widget_5)
        self.line_Selection_trips.setEnabled(False)
        self.line_Selection_trips.setStyleSheet("")
        self.line_Selection_trips.setObjectName("line_Selection_trips")
        self.gridLayout_8.addWidget(self.line_Selection_trips, 4, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setFamily("72")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("")
        self.label_17.setObjectName("label_17")
        self.gridLayout_8.addWidget(self.label_17, 6, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem1, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.widget_5, 5, 0, 1, 1)
        self.widget_7 = QtWidgets.QWidget(self.widget_4)
        self.widget_7.setObjectName("widget_7")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.widget_7)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.btnStart = QtWidgets.QPushButton(self.widget_7)
        self.btnStart.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnStart.setFont(font)
        self.btnStart.setStyleSheet("")
        self.btnStart.setObjectName("btnStart")
        self.gridLayout_12.addWidget(self.btnStart, 0, 0, 1, 1)
        self.btnStop = QtWidgets.QPushButton(self.widget_7)
        self.btnStop.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnStop.setFont(font)
        self.btnStop.setStyleSheet("")
        self.btnStop.setObjectName("btnStop")
        self.gridLayout_12.addWidget(self.btnStop, 0, 1, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_12, 0, 0, 1, 1)
        self.widget_8 = QtWidgets.QWidget(self.widget_7)
        self.widget_8.setObjectName("widget_8")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.widget_8)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_7 = QtWidgets.QLabel(self.widget_8)
        font = QtGui.QFont()
        font.setFamily("72")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("")
        self.label_7.setObjectName("label_7")
        self.gridLayout_14.addWidget(self.label_7, 0, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.widget_8)
        self.textBrowser.setStyleSheet("")
        self.textBrowser.setFrameShape(QtWidgets.QFrame.Box)
        self.textBrowser.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_14.addWidget(self.textBrowser, 1, 0, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_14, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.widget_8, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.widget_7, 5, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widget_4, 0, 1, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.widget)
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.widget_6)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_14 = QtWidgets.QLabel(self.widget_6)
        self.label_14.setStyleSheet("")
        self.label_14.setObjectName("label_14")
        self.gridLayout_10.addWidget(self.label_14, 0, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.widget_6)
        self.progressBar.setEnabled(False)
        self.progressBar.setStyleSheet("")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.progressBar.setTextVisible(False)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_10.addWidget(self.progressBar, 1, 0, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widget_6, 1, 0, 1, 2)
        self.gridLayout_6.addWidget(self.widget, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_2, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_12.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">mode</span></p></body></html>"))
        self.comboBox_direction.setItemText(0, _translate("Form", "direction 1"))
        self.comboBox_direction.setItemText(1, _translate("Form", "direction 2"))
        self.comboBox.setItemText(0, _translate("Form", "weekday"))
        self.comboBox.setItemText(1, _translate("Form", "date"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Weekday</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "example: 20211212"))
        self.lineDateInput.setText(_translate("Form", "20211212"))
        self.label_13.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Date</span></p></body></html>"))
        self.label_16.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Selection</span></p></body></html>"))
        self.label_17.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">detected date range</span></p></body></html>"))
        self.btnStart.setText(_translate("Form", "Create Table"))
        self.btnStop.setText(_translate("Form", "Stop"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Log</span></p></body></html>"))
        self.label_14.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">progress</span></p></body></html>"))
        self.progressBar.setFormat(_translate("Form", " %p%"))

from add_files.res import resource_boot
from add_files.res import resource_rc