# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\create_table_create.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(900, 590)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMaximumSize(QtCore.QSize(16777215, 590))
        Form.setStyleSheet("#Form {\n"
"border-style: solid;\n"
"border-color:  #f2f7f5;\n"
"background: #cfe2da; \n"
"\n"
"}\n"
"\n"
"#Form QListWidget {\n"
"    background-color: #F0FCF7;\n"
"   border-radius: 5px;\n"
"    text-align: center;\n"
"    color:#41312b;\n"
"}\n"
"\n"
"#Form QPushButton {\n"
"    background-color: #587b6d;\n"
"   border-radius: 10px;\n"
"    padding: 5px 5px 5px 5px;\n"
"    text-align: center;\n"
"    color:#f2b198;\n"
"}\n"
"\n"
"#Form QLineEdit {\n"
"    background-color: #F0FCF7;\n"
"   border-radius: 10px;\n"
"    padding: 5px 5px 5px 5px;\n"
"    text-align: center;\n"
"    color:#41312b;\n"
"}\n"
"\n"
"#Form QLabel {\n"
"    text-align: center;\n"
"    color:#41312b;\n"
"}\n"
"\n"
"#Form QComboBox {\n"
"    background-color: #587b6d;\n"
"   border-radius: 10px;\n"
"    padding: 5px 5px 5px 100px;\n"
"    text-align: center;\n"
"    color:#f2b198;\n"
"    \n"
"}\n"
"\n"
"#Form QPushButton:hover {\n"
"    background-color: #408d49;\n"
"   border-radius: 10px;\n"
"       color:#fde1d6;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.tableView_sorting_stops = QtWidgets.QTableView(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView_sorting_stops.sizePolicy().hasHeightForWidth())
        self.tableView_sorting_stops.setSizePolicy(sizePolicy)
        self.tableView_sorting_stops.setObjectName("tableView_sorting_stops")
        self.gridLayout.addWidget(self.tableView_sorting_stops, 2, 0, 1, 2)
        self.btnStop = QtWidgets.QPushButton(Form)
        self.btnStop.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnStop.setFont(font)
        self.btnStop.setStyleSheet("")
        self.btnStop.setObjectName("btnStop")
        self.gridLayout.addWidget(self.btnStop, 6, 1, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setStyleSheet("")
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 4, 0, 1, 1)
        self.listDatesWeekday = QtWidgets.QListWidget(Form)
        self.listDatesWeekday.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.listDatesWeekday.setFont(font)
        self.listDatesWeekday.setStyleSheet("")
        self.listDatesWeekday.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listDatesWeekday.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listDatesWeekday.setObjectName("listDatesWeekday")
        self.gridLayout_5.addWidget(self.listDatesWeekday, 3, 1, 3, 1)
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_5.addWidget(self.comboBox, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("72")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("")
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 2, 1, 1, 1)
        self.lineDateInput = QtWidgets.QLineEdit(Form)
        self.lineDateInput.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineDateInput.setFont(font)
        self.lineDateInput.setStyleSheet("")
        self.lineDateInput.setObjectName("lineDateInput")
        self.gridLayout_5.addWidget(self.lineDateInput, 3, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("72")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("")
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 2, 0, 1, 1)
        self.comboBox_direction = QtWidgets.QComboBox(Form)
        self.comboBox_direction.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_direction.setFont(font)
        self.comboBox_direction.setStyleSheet("")
        self.comboBox_direction.setObjectName("comboBox_direction")
        self.comboBox_direction.addItem("")
        self.comboBox_direction.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_direction, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.line_Selection_agency = QtWidgets.QLineEdit(Form)
        self.line_Selection_agency.setEnabled(False)
        self.line_Selection_agency.setStyleSheet("")
        self.line_Selection_agency.setObjectName("line_Selection_agency")
        self.gridLayout_3.addWidget(self.line_Selection_agency, 11, 0, 1, 1)
        self.line_Selection_trips = QtWidgets.QLineEdit(Form)
        self.line_Selection_trips.setEnabled(False)
        self.line_Selection_trips.setStyleSheet("")
        self.line_Selection_trips.setObjectName("line_Selection_trips")
        self.gridLayout_3.addWidget(self.line_Selection_trips, 12, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("72")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("")
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 3, 0, 1, 1)
        self.line_Selection_date_range = QtWidgets.QLineEdit(Form)
        self.line_Selection_date_range.setEnabled(False)
        self.line_Selection_date_range.setStyleSheet("")
        self.line_Selection_date_range.setObjectName("line_Selection_date_range")
        self.gridLayout_3.addWidget(self.line_Selection_date_range, 4, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("72")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("")
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 9, 0, 1, 1)
        self.line_Selection_format = QtWidgets.QLineEdit(Form)
        self.line_Selection_format.setEnabled(False)
        self.line_Selection_format.setStyleSheet("")
        self.line_Selection_format.setObjectName("line_Selection_format")
        self.gridLayout_3.addWidget(self.line_Selection_format, 10, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 0, 1, 1, 1)
        self.UseIndividualSorting = QtWidgets.QCheckBox(Form)
        self.UseIndividualSorting.setObjectName("UseIndividualSorting")
        self.gridLayout.addWidget(self.UseIndividualSorting, 1, 0, 1, 1)
        self.widget_8 = QtWidgets.QWidget(Form)
        self.widget_8.setObjectName("widget_8")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.widget_8)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.btnStart = QtWidgets.QPushButton(self.widget_8)
        self.btnStart.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnStart.setFont(font)
        self.btnStart.setStyleSheet("")
        self.btnStart.setObjectName("btnStart")
        self.gridLayout_15.addWidget(self.btnStart, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_8, 6, 0, 1, 1)
        self.btnContinueCreate = QtWidgets.QPushButton(Form)
        self.btnContinueCreate.setEnabled(False)
        self.btnContinueCreate.setObjectName("btnContinueCreate")
        self.gridLayout.addWidget(self.btnContinueCreate, 3, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btnStop.setText(_translate("Form", "Stop"))
        self.label_12.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">mode</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "example: 20211212"))
        self.comboBox.setItemText(0, _translate("Form", "weekday"))
        self.comboBox.setItemText(1, _translate("Form", "date"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Weekday</span></p></body></html>"))
        self.lineDateInput.setText(_translate("Form", "20211212"))
        self.label_13.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Date</span></p></body></html>"))
        self.comboBox_direction.setItemText(0, _translate("Form", "direction 1"))
        self.comboBox_direction.setItemText(1, _translate("Form", "direction 2"))
        self.label_17.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">detected date range</span></p></body></html>"))
        self.label_16.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Selection</span></p></body></html>"))
        self.UseIndividualSorting.setText(_translate("Form", "Use individual sorting"))
        self.btnStart.setText(_translate("Form", "Create Table"))
        self.btnContinueCreate.setText(_translate("Form", "Continue Creating Table"))
