# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\create_table_select.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(621, 662)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("72")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setStyleSheet("background-color:  #ffcbc0;\n"
"font: 75 8pt \"72\";")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.listAgencies = QtWidgets.QListWidget(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.listAgencies.setFont(font)
        self.listAgencies.setStyleSheet("background-color:  #ff9740;\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.listAgencies.setObjectName("listAgencies")
        self.gridLayout.addWidget(self.listAgencies, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setStyleSheet("background-color:  #ffcbc0;\n"
"font: 75 8pt \"72\";")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.listRoutes = QtWidgets.QListWidget(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.listRoutes.setFont(font)
        self.listRoutes.setStyleSheet("background-color:  #ff9740;\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.listRoutes.setObjectName("listRoutes")
        self.gridLayout.addWidget(self.listRoutes, 3, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Agencies</span></p></body></html>"))
        self.label_8.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Trips</span></p></body></html>"))
