# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\download_gtfs.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(753, 448)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("background-color:  #ffcbc0;\n"
"border-radius: 0px;")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tabDownloadGTFS = QtWidgets.QWidget()
        self.tabDownloadGTFS.setObjectName("tabDownloadGTFS")
        self.gridLayout = QtWidgets.QGridLayout(self.tabDownloadGTFS)
        self.gridLayout.setObjectName("gridLayout")
        self.btnLoadOnlineData_2 = QtWidgets.QPushButton(self.tabDownloadGTFS)
        self.btnLoadOnlineData_2.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnLoadOnlineData_2.setFont(font)
        self.btnLoadOnlineData_2.setStyleSheet("background-color: orange;\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.btnLoadOnlineData_2.setObjectName("btnLoadOnlineData_2")
        self.gridLayout.addWidget(self.btnLoadOnlineData_2, 3, 4, 1, 1)
        self.comboBox_online = QtWidgets.QComboBox(self.tabDownloadGTFS)
        self.comboBox_online.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_online.setFont(font)
        self.comboBox_online.setStyleSheet("background-color:  #ff9740;\n"
"border-style: outset;\n"
"border-width:0px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.comboBox_online.setObjectName("comboBox_online")
        self.comboBox_online.addItem("")
        self.comboBox_online.addItem("")
        self.gridLayout.addWidget(self.comboBox_online, 1, 1, 1, 2)
        self.btnLoadFromPath = QtWidgets.QPushButton(self.tabDownloadGTFS)
        self.btnLoadFromPath.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnLoadFromPath.setFont(font)
        self.btnLoadFromPath.setStyleSheet("background-color: orange;\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.btnLoadFromPath.setObjectName("btnLoadFromPath")
        self.gridLayout.addWidget(self.btnLoadFromPath, 3, 0, 1, 2)
        self.btnLoadOnlineData = QtWidgets.QPushButton(self.tabDownloadGTFS)
        self.btnLoadOnlineData.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnLoadOnlineData.setFont(font)
        self.btnLoadOnlineData.setStyleSheet("background-color: orange;\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.btnLoadOnlineData.setObjectName("btnLoadOnlineData")
        self.gridLayout.addWidget(self.btnLoadOnlineData, 3, 2, 1, 2)
        self.listTabGTFSDATA = QtWidgets.QListWidget(self.tabDownloadGTFS)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.listTabGTFSDATA.setFont(font)
        self.listTabGTFSDATA.setStyleSheet("background-color:  #ff9740;\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.listTabGTFSDATA.setObjectName("listTabGTFSDATA")
        self.gridLayout.addWidget(self.listTabGTFSDATA, 4, 0, 1, 5)
        self.GTFSInputPath = QtWidgets.QLineEdit(self.tabDownloadGTFS)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.GTFSInputPath.setFont(font)
        self.GTFSInputPath.setStyleSheet("background-color: #fdfefe;\n"
"border-style: outset;\n"
"border-width: 0.5px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 1px;")
        self.GTFSInputPath.setObjectName("GTFSInputPath")
        self.gridLayout.addWidget(self.GTFSInputPath, 0, 1, 1, 2)
        self.label_15 = QtWidgets.QLabel(self.tabDownloadGTFS)
        font = QtGui.QFont()
        font.setFamily("72")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("background-color:  #ffcbc0;\n"
"font: 75 8pt \"72\";")
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 0, 0, 2, 1)
        self.btnGetDir = QtWidgets.QPushButton(self.tabDownloadGTFS)
        self.btnGetDir.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnGetDir.setFont(font)
        self.btnGetDir.setStyleSheet("background-color: orange;\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.btnGetDir.setObjectName("btnGetDir")
        self.gridLayout.addWidget(self.btnGetDir, 0, 3, 1, 1)
        self.tabWidget.addTab(self.tabDownloadGTFS, "")
        self.tabDefineSorting = QtWidgets.QWidget()
        self.tabDefineSorting.setObjectName("tabDefineSorting")
        self.listTabSort = QtWidgets.QListWidget(self.tabDefineSorting)
        self.listTabSort.setGeometry(QtCore.QRect(20, 80, 371, 141))
        self.listTabSort.setStyleSheet("background-color:  #ff9740;\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.listTabSort.setObjectName("listTabSort")
        self.tabWidget.addTab(self.tabDefineSorting, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btnLoadOnlineData_2.setText(_translate("Form", "Download Selected Data"))
        self.comboBox_online.setItemText(0, _translate("Form", "opendata.ruhr"))
        self.comboBox_online.setItemText(1, _translate("Form", "opendata.vbb"))
        self.btnLoadFromPath.setText(_translate("Form", "Load From Path"))
        self.btnLoadOnlineData.setText(_translate("Form", "Load Online Data"))
        self.GTFSInputPath.setText(_translate("Form", "C:/Tmp/"))
        self.label_15.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">GTFS-Data</span></p></body></html>"))
        self.btnGetDir.setText(_translate("Form", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDownloadGTFS), _translate("Form", "GTFS Load Options"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDefineSorting), _translate("Form", "Sort Options"))
