# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\create_table_create.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from view.custom_table_view import customTableView


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(900, 590)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMaximumSize(QtCore.QSize(16777215, 590))
        Form.setStyleSheet("#Form {\n"
"border-style: solid;\n"
"border-color:  #26302c;\n"
"background: #cfe2da; \n"
"padding: 2px;\n"
"box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\n"
"}\n"
"\n"
"#Form QListWidget {\n"
"    background-color: #F0FCF7;\n"
"   border-radius: 5px;\n"
"    text-align: center;\n"
"    color:#26302c;\n"
"}\n"
"\n"
"#Form QListWidget::item {\n"
"    padding: 10px;\n"
"    border-bottom: 1px solid #ddd;\n"
"}\n"
"\n"
"#Form QPushButton {\n"
"    background-color: #587b6d;\n"
"    border-radius: 10px;\n"
"    margin-bottom: 15px;\n"
"    padding: 5px 5px 5px 5px;\n"
"    text-align: center;\n"
"    color:#f2b198;\n"
"}\n"
"\n"
"#Form QLineEdit {\n"
"    background-color: #F0FCF7;\n"
"   border-radius: 10px;\n"
"    padding: 5px 5px 5px 5px;\n"
"    text-align: center;\n"
"    color:#41312b;\n"
"}\n"
"\n"
"#Form QLabel {\n"
"    text-align: center;\n"
"    color: #41312b;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    margin-bottom: 10px;\n"
"}\n"
"\n"
"#Form QComboBox {\n"
"    background-color: #587b6d;\n"
"   border-radius: 10px;\n"
"    padding: 5px 5px 5px 100px;\n"
"    text-align: left;\n"
"    color:#f2b198;\n"
"    border: 1px solid #ccc;\n"
"    appearance: none;\n"
"    -webkit-appearance: none;\n"
"    -moz-appearance: none;\n"
"}\n"
"\n"
"#Form QComboBox::drop-down {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: right bottom;\n"
"    width: 40px;\n"
"    border-left: 1px solid #ccc;\n"
"}\n"
"\n"
"#Form QPushButton:hover {\n"
"    background-color: #408d49;\n"
"   border-radius: 10px;\n"
"       color:#fde1d6;\n"
"}\n"
"\n"
"#Form QTableView {\n"
"    color: black;\n"
"    gridline-color: black;\n"
"    border-color: #f2f7f5;\n"
"    font: 10px;\n"
"    background: #eaeaea;\n"
"    padding: 10px;\n"
"    border: 1px solid #f2f7f5;\n"
"}\n"
"\n"
"#Form QTableView::item {\n"
"    padding: 5px;\n"
"    border-bottom: 1px solid #ddd;\n"
"}\n"
"\n"
"#Form QTableView::item:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #F0FCF7, stop: 1 #EAEAEA);\n"
"    border: 1px solid #587b6d;\n"
"}\n"
"\n"
"#Form QTableView::item:selected {\n"
"    background: #587b6d;\n"
"    color: #26302c;\n"
"    border: 1px solid #587b6d;\n"
"}\n"
"\n"
"#Form QTableView::item:selected:active {\n"
"    background: #408d49;\n"
"    color: #26302c;\n"
"}\n"
"\n"
"#Form QTableCornerButton::section {\n"
"    background: #587b6d;\n"
"    border: 2px outset #587b6d;\n"
"}\n"
"\n"
"#Form QTableView::indicator:checked {\n"
"    background-color: #408d49;\n"
"    color: #26302c;\n"
"}\n"
"\n"
"#Form QTableView::indicator:unchecked {\n"
"    background-color: #f2f7f5;\n"
"    color: #587b6d;\n"
"}\n"
"\n"
"#Form QScrollBar:vertical {\n"
"    background: #F0FCF7;\n"
"    width: 10px;\n"
"}\n"
"\n"
"#Form QScrollBar::handle:vertical {\n"
"    background: #587b6d;\n"
"    min-height: 50px;\n"
"}\n"
"\n"
"#Form QScrollBar::add-page:vertical {\n"
"    background: #F0FCF7;\n"
"}\n"
"\n"
"#Form QScrollBar::sub-page:vertical {\n"
"    background: #F0FCF7;\n"
"}\n"
"\n"
"#Form QScrollBar:horizontal {\n"
"    background: #F0FCF7;\n"
"    height: 10px;\n"
"}\n"
"\n"
"#Form QScrollBar::handle:horizontal {\n"
"    background: #587b6d;\n"
"    min-width: 50px;\n"
"}\n"
"\n"
"#Form QScrollBar::add-page:horizontal {\n"
"    background: #F0FCF7;\n"
"}\n"
"\n"
"#Form QScrollBar::sub-page:horizontal {\n"
"    background: #F0FCF7;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.btnContinueCreate = QtWidgets.QPushButton(Form)
        self.btnContinueCreate.setEnabled(False)
        self.btnContinueCreate.setObjectName("btnContinueCreate")
        self.gridLayout_5.addWidget(self.btnContinueCreate, 10, 0, 1, 1)
        #self.tableView_sorting_stops = QtWidgets.QTableView(Form)
        self.tableView_sorting_stops = customTableView()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView_sorting_stops.sizePolicy().hasHeightForWidth())
        self.tableView_sorting_stops.setSizePolicy(sizePolicy)
        self.tableView_sorting_stops.setObjectName("tableView_sorting_stops")
        self.gridLayout_5.addWidget(self.tableView_sorting_stops, 10, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 4, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem, 3, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setStyleSheet("")
        self.label_12.setObjectName("label_12")
        self.gridLayout_6.addWidget(self.label_12, 3, 1, 1, 1)
        self.comboBox_direction = QtWidgets.QComboBox(Form)
        self.comboBox_direction.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_direction.setFont(font)
        self.comboBox_direction.setStyleSheet("")
        self.comboBox_direction.setObjectName("comboBox_direction")
        self.comboBox_direction.addItem("")
        self.comboBox_direction.addItem("")
        self.gridLayout_6.addWidget(self.comboBox_direction, 4, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_6.addWidget(self.comboBox, 5, 1, 1, 1)
        self.UseIndividualSorting = QtWidgets.QCheckBox(Form)
        self.UseIndividualSorting.setObjectName("UseIndividualSorting")
        self.gridLayout_6.addWidget(self.UseIndividualSorting, 4, 2, 1, 1)
        self.btnStart = QtWidgets.QPushButton(Form)
        self.btnStart.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnStart.setFont(font)
        self.btnStart.setStyleSheet("")
        self.btnStart.setObjectName("btnStart")
        self.gridLayout_6.addWidget(self.btnStart, 6, 1, 1, 1)
        self.btnStop = QtWidgets.QPushButton(Form)
        self.btnStop.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnStop.setFont(font)
        self.btnStop.setStyleSheet("")
        self.btnStop.setObjectName("btnStop")
        self.gridLayout_6.addWidget(self.btnStop, 7, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_6 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("72")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("")
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 4, 1, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(Form)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout_4.addWidget(self.dateEdit, 1, 1, 1, 1)
        self.listDatesWeekday = QtWidgets.QListWidget(Form)
        self.listDatesWeekday.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.listDatesWeekday.setFont(font)
        self.listDatesWeekday.setStyleSheet("")
        self.listDatesWeekday.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listDatesWeekday.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listDatesWeekday.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.listDatesWeekday.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.listDatesWeekday.setObjectName("listDatesWeekday")
        self.gridLayout_4.addWidget(self.listDatesWeekday, 5, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("72")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("")
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 2, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("72")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("")
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 0, 1, 1, 1)
        self.line_Selection_date_range = QtWidgets.QLineEdit(Form)
        self.line_Selection_date_range.setEnabled(False)
        self.line_Selection_date_range.setStyleSheet("")
        self.line_Selection_date_range.setObjectName("line_Selection_date_range")
        self.gridLayout_4.addWidget(self.line_Selection_date_range, 3, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_4, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 3, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btnContinueCreate.setText(_translate("Form", "Continue Creating Table"))
        self.label_12.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Mode Settings</span></p></body></html>"))
        self.comboBox_direction.setItemText(0, _translate("Form", "direction 1"))
        self.comboBox_direction.setItemText(1, _translate("Form", "direction 2"))
        self.comboBox.setItemText(0, _translate("Form", "Date"))
        self.comboBox.setItemText(1, _translate("Form", "Weekday"))
        self.comboBox.setItemText(2, _translate("Form", "Umlaufplan Date"))
        self.comboBox.setItemText(3, _translate("Form", "Umlaufplan Weekday"))
        self.UseIndividualSorting.setText(_translate("Form", "Use individual sorting"))
        self.btnStart.setText(_translate("Form", "Create Table"))
        self.btnStop.setText(_translate("Form", "Stop"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Weekday</span></p></body></html>"))
        self.label_17.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Detected Date Range</span></p></body></html>"))
        self.label_13.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Date</span></p></body></html>"))

from view.ui.res import resource_boot
from view.ui.res import resource_rc