# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\create_table_select.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(900, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(900, 400))
        Form.setMaximumSize(QtCore.QSize(900, 700))
        Form.setStyleSheet("#Form {\n"
"border-style: solid;\n"
"border-color:  #f2f7f5;\n"
"background: #cfe2da; \n"
"\n"
"}\n"
"\n"
"#Form QListWidget {\n"
"    background-color: #F0FCF7;\n"
"   border-radius: 10px;\n"
"    padding: 5px 5px 5px 5px;\n"
"    text-align: center;\n"
"    color:#41312b;\n"
"}\n"
"\n"
"#Form QPushButton {\n"
"    background-color: #587b6d;\n"
"   border-radius: 10px;\n"
"    padding: 5px 5px 5px 5px;\n"
"    text-align: center;\n"
"    color:#f2b198;\n"
"}\n"
"\n"
"#Form QLineEdit {\n"
"    background-color: #F0FCF7;\n"
"   border-radius: 10px;\n"
"    padding: 5px 5px 5px 5px;\n"
"    text-align: center;\n"
"    color:#41312b;\n"
"}\n"
"\n"
"#Form QLabel {\n"
"   border-radius: 10px;\n"
"    padding: 5px 5px 5px 5px;\n"
"    text-align: center;\n"
"    color:#41312b;\n"
"}\n"
"\n"
"#Form QComboBox {\n"
"    background-color: #587b6d;\n"
"   border-radius: 10px;\n"
"    padding: 5px 5px 5px 100px;\n"
"    text-align: center;\n"
"    color:#f2b198;\n"
"    \n"
"}\n"
"\n"
"#Form QPushButton:hover {\n"
"    background-color: #408d49;\n"
"   border-radius: 10px;\n"
"       color:#fde1d6;\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.AgenciesTableView = QtWidgets.QTableView(Form)
        self.AgenciesTableView.setObjectName("AgenciesTableView")
        self.gridLayout.addWidget(self.AgenciesTableView, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("72")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setStyleSheet("")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setStyleSheet("")
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 1)
        self.TripsTableView = QtWidgets.QTableView(Form)
        self.TripsTableView.setObjectName("TripsTableView")
        self.gridLayout_2.addWidget(self.TripsTableView, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Agencies</span></p></body></html>"))
        self.label_8.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Trips</span></p></body></html>"))

from view.ui.res import resource_boot
from view.ui.res import resource_rc