# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\create_table_import.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1100, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        Form.setMaximumSize(QtCore.QSize(1100, 900))
        Form.setLayoutDirection(QtCore.Qt.LeftToRight)
        Form.setStyleSheet("#Form {\n"
"border-style: solid;\n"
"border-color:  #f2f7f5;\n"
"background: #cfe2da; \n"
"\n"
"}\n"
"\n"
"#Form QPushButton {\n"
"    background-color: #587b6d;\n"
"   border-radius: 10px;\n"
"    padding: 5px 5px 5px 5px;\n"
"    text-align: center;\n"
"    color:#f2b198;\n"
"}\n"
"\n"
"#Form QLineEdit {\n"
"    background-color: #F0FCF7;\n"
"   border-radius: 10px;\n"
"    padding: 5px 5px 5px 5px;\n"
"    text-align: center;\n"
"    color:#41312b;\n"
"}\n"
"\n"
"#Form QLabel {\n"
"   border-radius: 10px;\n"
"    padding: 5px 5px 5px 5px;\n"
"    text-align: center;\n"
"    color:#41312b;\n"
"}\n"
"\n"
"#Form QComboBox {\n"
"    background-color: #587b6d;\n"
"   border-radius: 10px;\n"
"    padding: 5px 5px 5px 100px;\n"
"    text-align: center;\n"
"    color:#f2b198;\n"
"    \n"
"}\n"
"\n"
"#Form QPushButton:hover {\n"
"    background-color: #408d49;\n"
"   border-radius: 10px;\n"
"       color:#fde1d6;\n"
"}\n"
"")
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout.addLayout(self.gridLayout_5, 10, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 18, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 18, 4, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout.addLayout(self.gridLayout_4, 0, 3, 1, 1)
        self.btnRestart = QtWidgets.QPushButton(Form)
        self.btnRestart.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnRestart.setFont(font)
        self.btnRestart.setStyleSheet("")
        self.btnRestart.setObjectName("btnRestart")
        self.gridLayout.addWidget(self.btnRestart, 8, 1, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btnGetPickleFile = QtWidgets.QPushButton(Form)
        self.btnGetPickleFile.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnGetPickleFile.setFont(font)
        self.btnGetPickleFile.setStyleSheet("")
        self.btnGetPickleFile.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icons/bootstrap-icons-1.10.3/file-earmark-arrow-up.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnGetPickleFile.setIcon(icon)
        self.btnGetPickleFile.setObjectName("btnGetPickleFile")
        self.gridLayout_3.addWidget(self.btnGetPickleFile, 3, 2, 1, 1)
        self.checkBox_savepickle = QtWidgets.QCheckBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_savepickle.sizePolicy().hasHeightForWidth())
        self.checkBox_savepickle.setSizePolicy(sizePolicy)
        self.checkBox_savepickle.setObjectName("checkBox_savepickle")
        self.gridLayout_3.addWidget(self.checkBox_savepickle, 3, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("")
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 1, 0, 1, 1)
        self.btnGetOutputDir = QtWidgets.QPushButton(Form)
        self.btnGetOutputDir.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnGetOutputDir.setFont(font)
        self.btnGetOutputDir.setStyleSheet("")
        self.btnGetOutputDir.setText("")
        self.btnGetOutputDir.setIcon(icon)
        self.btnGetOutputDir.setObjectName("btnGetOutputDir")
        self.gridLayout_3.addWidget(self.btnGetOutputDir, 2, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("")
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 2, 0, 1, 1)
        self.picklesavename = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.picklesavename.setFont(font)
        self.picklesavename.setStyleSheet("")
        self.picklesavename.setText("")
        self.picklesavename.setObjectName("picklesavename")
        self.gridLayout_3.addWidget(self.picklesavename, 3, 1, 1, 1)
        self.comboBox_display = QtWidgets.QComboBox(Form)
        self.comboBox_display.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_display.setFont(font)
        self.comboBox_display.setStyleSheet("")
        self.comboBox_display.setObjectName("comboBox_display")
        self.comboBox_display.addItem("")
        self.comboBox_display.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_display, 4, 1, 1, 1)
        self.btnGetFile = QtWidgets.QPushButton(Form)
        self.btnGetFile.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnGetFile.setFont(font)
        self.btnGetFile.setStyleSheet("")
        self.btnGetFile.setText("")
        self.btnGetFile.setIcon(icon)
        self.btnGetFile.setObjectName("btnGetFile")
        self.gridLayout_3.addWidget(self.btnGetFile, 1, 2, 1, 1)
        self.lineOutputPath = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineOutputPath.setFont(font)
        self.lineOutputPath.setStyleSheet("")
        self.lineOutputPath.setText("")
        self.lineOutputPath.setObjectName("lineOutputPath")
        self.gridLayout_3.addWidget(self.lineOutputPath, 2, 1, 1, 1)
        self.lineInputPath = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineInputPath.setFont(font)
        self.lineInputPath.setStyleSheet("")
        self.lineInputPath.setText("")
        self.lineInputPath.setObjectName("lineInputPath")
        self.gridLayout_3.addWidget(self.lineInputPath, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 6, 1, 1, 1)
        self.btnImport = QtWidgets.QPushButton(Form)
        self.btnImport.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnImport.setFont(font)
        self.btnImport.setStyleSheet("")
        self.btnImport.setObjectName("btnImport")
        self.gridLayout.addWidget(self.btnImport, 7, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 1, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btnRestart.setText(_translate("Form", "Restart Import"))
        self.checkBox_savepickle.setToolTip(_translate("Form", "saves data to faster format"))
        self.checkBox_savepickle.setWhatsThis(_translate("Form", "saves data to faster format"))
        self.checkBox_savepickle.setText(_translate("Form", "save data to pickle format"))
        self.label_11.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">input data</span></p></body></html>"))
        self.label_10.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">output path</span></p></body></html>"))
        self.picklesavename.setPlaceholderText(_translate("Form", "C:/Tmp/GTFS.zip"))
        self.comboBox_display.setItemText(0, _translate("Form", "time format 1"))
        self.comboBox_display.setItemText(1, _translate("Form", "time format 2"))
        self.lineOutputPath.setPlaceholderText(_translate("Form", "C:/Tmp/"))
        self.lineInputPath.setPlaceholderText(_translate("Form", "C:/Tmp/GTFS.zip"))
        self.btnImport.setText(_translate("Form", "Start Import"))


from view.ui.res import resource_boot
from view.ui.res import resource_rc