# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\download_gtfs.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMaximumSize(QtCore.QSize(1000, 400))
        Form.setLayoutDirection(QtCore.Qt.LeftToRight)
        Form.setStyleSheet("#Form {\n"
"border-style: solid;\n"
"border-color:  #f2f7f5;\n"
"background: #cfe2da; \n"
"\n"
"}\n"
"\n"
"#Form QPushButton {\n"
"    background-color: #587b6d;\n"
"   border-radius: 10px;\n"
"    padding: 5px 5px 5px 5px;\n"
"    text-align: center;\n"
"    color:#f2b198;\n"
"}\n"
"\n"
"#Form QLineEdit {\n"
"    background-color: #F0FCF7;\n"
"   border-radius: 10px;\n"
"    padding: 5px 5px 5px 5px;\n"
"    text-align: center;\n"
"    color:#41312b;\n"
"}\n"
"\n"
"#Form QLabel {\n"
"   border-radius: 10px;\n"
"    padding: 5px 5px 5px 5px;\n"
"    text-align: center;\n"
"    color:#41312b;\n"
"}\n"
"\n"
"#Form QComboBox {\n"
"    background-color: #587b6d;\n"
"   border-radius: 10px;\n"
"    padding: 5px 5px 5px 100px;\n"
"    text-align: center;\n"
"    color:#f2b198;\n"
"    \n"
"}\n"
"\n"
"#Form QPushButton:hover {\n"
"    background-color: #408d49;\n"
"   border-radius: 10px;\n"
"       color:#fde1d6;\n"
"}\n"
"")
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridWidget = QtWidgets.QWidget(Form)
        self.gridWidget.setStyleSheet("#Form QTableView {\n"
"    background-color: #F0FCF7;\n"
"   border-radius: 10px;\n"
"    padding: 5px 5px 5px 5px;\n"
"    text-align: center;\n"
"    color:#41312b;\n"
"}")
        self.gridWidget.setObjectName("gridWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableView = QtWidgets.QTableView(self.gridWidget)
        self.tableView.setObjectName("tableView")
        self.gridLayout_2.addWidget(self.tableView, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.gridWidget, 0, 1, 1, 1)
        self.gridWidget1 = QtWidgets.QWidget(Form)
        self.gridWidget1.setObjectName("gridWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.gridWidget1)
        self.gridLayout.setObjectName("gridLayout")
        self.label_11 = QtWidgets.QLabel(self.gridWidget1)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("")
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineInputPath_2 = QtWidgets.QLineEdit(self.gridWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineInputPath_2.setFont(font)
        self.lineInputPath_2.setStyleSheet("")
        self.lineInputPath_2.setText("")
        self.lineInputPath_2.setObjectName("lineInputPath_2")
        self.gridLayout.addWidget(self.lineInputPath_2, 2, 1, 1, 1)
        self.comboBox_display = QtWidgets.QComboBox(self.gridWidget1)
        self.comboBox_display.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_display.setFont(font)
        self.comboBox_display.setStyleSheet("")
        self.comboBox_display.setObjectName("comboBox_display")
        self.comboBox_display.addItem("")
        self.comboBox_display.addItem("")
        self.gridLayout.addWidget(self.comboBox_display, 5, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 1, 1, 1)
        self.gridLayout_3.addWidget(self.gridWidget1, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btnLoadOnlineData = QtWidgets.QPushButton(Form)
        self.btnLoadOnlineData.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnLoadOnlineData.setFont(font)
        self.btnLoadOnlineData.setStyleSheet("")
        self.btnLoadOnlineData.setObjectName("btnLoadOnlineData")
        self.gridLayout_4.addWidget(self.btnLoadOnlineData, 0, 0, 1, 1)
        self.btnDownloadSelected = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnDownloadSelected.setFont(font)
        self.btnDownloadSelected.setObjectName("btnDownloadSelected")
        self.gridLayout_4.addWidget(self.btnDownloadSelected, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_4, 1, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_11.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Save Location</span></p></body></html>"))
        self.lineInputPath_2.setPlaceholderText(_translate("Form", "C:/Tmp/"))
        self.comboBox_display.setItemText(0, _translate("Form", "opendata.ruhr"))
        self.comboBox_display.setItemText(1, _translate("Form", "opendata.vbb"))
        self.btnLoadOnlineData.setText(_translate("Form", "Load Online Data"))
        self.btnDownloadSelected.setText(_translate("Form", "Download Selected Data"))

from view.ui.res import resource_boot
from view.ui.res import resource_rc
